base: 'http://localhost/welcome-firose/public/'
dependencies:
  - firose/welcome
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US
    navigationTitle: English
    flag: us
rootPageId: 1
routes: {  }
